# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dovizIslemleri.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_paraDonustur(object):
    def setupUi(self, paraDonustur):
        paraDonustur.setObjectName("paraDonustur")
        paraDonustur.resize(424, 550)
        self.lnTC = QtWidgets.QLineEdit(paraDonustur)
        self.lnTC.setGeometry(QtCore.QRect(170, 110, 113, 21))
        self.lnTC.setObjectName("lnTC")
        self.label_2 = QtWidgets.QLabel(paraDonustur)
        self.label_2.setGeometry(QtCore.QRect(110, 210, 71, 20))
        self.label_2.setObjectName("label_2")
        self.pbParaDonustur = QtWidgets.QPushButton(paraDonustur)
        self.pbParaDonustur.setGeometry(QtCore.QRect(150, 430, 121, 32))
        self.pbParaDonustur.setObjectName("pbParaDonustur")
        self.label_3 = QtWidgets.QLabel(paraDonustur)
        self.label_3.setGeometry(QtCore.QRect(230, 210, 101, 16))
        self.label_3.setObjectName("label_3")
        self.pbGeri = QtWidgets.QPushButton(paraDonustur)
        self.pbGeri.setGeometry(QtCore.QRect(160, 510, 100, 32))
        self.pbGeri.setObjectName("pbGeri")
        self.label = QtWidgets.QLabel(paraDonustur)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 61))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(paraDonustur)
        self.label_4.setGeometry(QtCore.QRect(70, 110, 91, 21))
        self.label_4.setObjectName("label_4")
        self.labelDurum = QtWidgets.QLabel(paraDonustur)
        self.labelDurum.setGeometry(QtCore.QRect(190, 470, 101, 20))
        self.labelDurum.setText("")
        self.labelDurum.setObjectName("labelDurum")
        self.lnParaMiktari = QtWidgets.QLineEdit(paraDonustur)
        self.lnParaMiktari.setGeometry(QtCore.QRect(220, 250, 125, 21))
        self.lnParaMiktari.setObjectName("lnParaMiktari")
        self.lcdNumber = QtWidgets.QLCDNumber(paraDonustur)
        self.lcdNumber.setGeometry(QtCore.QRect(220, 290, 125, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.pbHesapla = QtWidgets.QPushButton(paraDonustur)
        self.pbHesapla.setGeometry(QtCore.QRect(160, 360, 100, 32))
        self.pbHesapla.setObjectName("pbHesapla")
        self.labelSonuc = QtWidgets.QLabel(paraDonustur)
        self.labelSonuc.setGeometry(QtCore.QRect(190, 400, 91, 21))
        self.labelSonuc.setText("")
        self.labelSonuc.setObjectName("labelSonuc")
        self.widget = QtWidgets.QWidget(paraDonustur)
        self.widget.setGeometry(QtCore.QRect(90, 240, 121, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cmParaTuru = QtWidgets.QComboBox(self.widget)
        self.cmParaTuru.setObjectName("cmParaTuru")
        self.cmParaTuru.addItem("")
        self.cmParaTuru.addItem("")
        self.verticalLayout_2.addWidget(self.cmParaTuru)
        self.cmParaTuruCevir = QtWidgets.QComboBox(self.widget)
        self.cmParaTuruCevir.setObjectName("cmParaTuruCevir")
        self.cmParaTuruCevir.addItem("")
        self.cmParaTuruCevir.addItem("")
        self.verticalLayout_2.addWidget(self.cmParaTuruCevir)

        self.retranslateUi(paraDonustur)
        self.cmParaTuru.setCurrentIndex(-1)
        self.cmParaTuruCevir.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(paraDonustur)

    def retranslateUi(self, paraDonustur):
        _translate = QtCore.QCoreApplication.translate
        paraDonustur.setWindowTitle(_translate("paraDonustur", "Form"))
        self.label_2.setText(_translate("paraDonustur", "<html><head/><body><p align=\"center\">Para Türü</p></body></html>"))
        self.pbParaDonustur.setText(_translate("paraDonustur", "Para Dönüştür"))
        self.label_3.setText(_translate("paraDonustur", "<html><head/><body><p align=\"center\">Para Tutarı</p></body></html>"))
        self.pbGeri.setText(_translate("paraDonustur", "Geri"))
        self.label.setText(_translate("paraDonustur", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; color:#0433ff;\"> Döviz İşlemleri</span></p></body></html>"))
        self.label_4.setText(_translate("paraDonustur", "TC Numarası"))
        self.pbHesapla.setText(_translate("paraDonustur", "Hesapla"))
        self.cmParaTuru.setItemText(0, _translate("paraDonustur", "Dolar"))
        self.cmParaTuru.setItemText(1, _translate("paraDonustur", "Tl"))
        self.cmParaTuruCevir.setItemText(0, _translate("paraDonustur", "Dolar"))
        self.cmParaTuruCevir.setItemText(1, _translate("paraDonustur", "Tl"))
