# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KullaniciGirisEkrani(object):
    def setupUi(self, KullaniciGirisEkrani):
        KullaniciGirisEkrani.setObjectName("KullaniciGirisEkrani")
        KullaniciGirisEkrani.setEnabled(True)
        KullaniciGirisEkrani.resize(424, 550)
        self.centralwidget = QtWidgets.QWidget(KullaniciGirisEkrani)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 60, 191, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bank (1).jpg"))
        self.label.setObjectName("label")
        self.pbGiris = QtWidgets.QPushButton(self.centralwidget)
        self.pbGiris.setGeometry(QtCore.QRect(112, 290, 212, 32))
        self.pbGiris.setObjectName("pbGiris")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setEnabled(True)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 160, 201, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lneKullaniAd = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneKullaniAd.setEnabled(True)
        self.lneKullaniAd.setObjectName("lneKullaniAd")
        self.verticalLayout.addWidget(self.lneKullaniAd)
        self.lneKullaniciSifre = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneKullaniciSifre.setEnabled(True)
        self.lneKullaniciSifre.setObjectName("lneKullaniciSifre")
        self.verticalLayout.addWidget(self.lneKullaniciSifre)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setEnabled(True)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 160, 91, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(140, 370, 161, 66))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pbYeniKayt = QtWidgets.QPushButton(self.layoutWidget2)
        self.pbYeniKayt.setObjectName("pbYeniKayt")
        self.verticalLayout_3.addWidget(self.pbYeniKayt)
        self.pbSorunSifre = QtWidgets.QPushButton(self.layoutWidget2)
        self.pbSorunSifre.setObjectName("pbSorunSifre")
        self.verticalLayout_3.addWidget(self.pbSorunSifre)
        KullaniciGirisEkrani.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(KullaniciGirisEkrani)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 424, 24))
        self.menubar.setObjectName("menubar")
        KullaniciGirisEkrani.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(KullaniciGirisEkrani)
        self.statusBar.setObjectName("statusBar")
        KullaniciGirisEkrani.setStatusBar(self.statusBar)

        self.retranslateUi(KullaniciGirisEkrani)
        QtCore.QMetaObject.connectSlotsByName(KullaniciGirisEkrani)

    def retranslateUi(self, KullaniciGirisEkrani):
        _translate = QtCore.QCoreApplication.translate
        KullaniciGirisEkrani.setWindowTitle(_translate("KullaniciGirisEkrani", "MainWindow"))
        self.pbGiris.setText(_translate("KullaniciGirisEkrani", "Giriş"))
        self.label_2.setText(_translate("KullaniciGirisEkrani", "<html><head/><body><p><span style=\" color:#0433ff;\">Kullanıcı Adı</span></p></body></html>"))
        self.label_4.setText(_translate("KullaniciGirisEkrani", "<html><head/><body><p><span style=\" color:#0433ff;\">Kullanıcı Şifre</span></p></body></html>"))
        self.pbYeniKayt.setText(_translate("KullaniciGirisEkrani", "Yeni Kayıt"))
        self.pbSorunSifre.setText(_translate("KullaniciGirisEkrani", "Şifremi kaybettim"))
