# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paraCek.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_paraCekme(object):
    def setupUi(self, paraCekme):
        paraCekme.setObjectName("paraCekme")
        paraCekme.resize(424, 550)
        self.label_2 = QtWidgets.QLabel(paraCekme)
        self.label_2.setGeometry(QtCore.QRect(110, 175, 71, 20))
        self.label_2.setObjectName("label_2")
        self.lnParaMiktari = QtWidgets.QLineEdit(paraCekme)
        self.lnParaMiktari.setGeometry(QtCore.QRect(220, 240, 113, 21))
        self.lnParaMiktari.setObjectName("lnParaMiktari")
        self.label_3 = QtWidgets.QLabel(paraCekme)
        self.label_3.setGeometry(QtCore.QRect(230, 175, 101, 16))
        self.label_3.setObjectName("label_3")
        self.cmParaTuru = QtWidgets.QComboBox(paraCekme)
        self.cmParaTuru.setGeometry(QtCore.QRect(100, 230, 103, 41))
        self.cmParaTuru.setObjectName("cmParaTuru")
        self.cmParaTuru.addItem("")
        self.cmParaTuru.addItem("")
        self.label_4 = QtWidgets.QLabel(paraCekme)
        self.label_4.setGeometry(QtCore.QRect(100, 110, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(paraCekme)
        self.label.setGeometry(QtCore.QRect(20, 10, 201, 61))
        self.label.setObjectName("label")
        self.labelDurum = QtWidgets.QLabel(paraCekme)
        self.labelDurum.setGeometry(QtCore.QRect(170, 290, 101, 20))
        self.labelDurum.setText("")
        self.labelDurum.setObjectName("labelDurum")
        self.lnTC = QtWidgets.QLineEdit(paraCekme)
        self.lnTC.setGeometry(QtCore.QRect(210, 110, 113, 21))
        self.lnTC.setObjectName("lnTC")
        self.pbGeri = QtWidgets.QPushButton(paraCekme)
        self.pbGeri.setGeometry(QtCore.QRect(160, 510, 100, 32))
        self.pbGeri.setObjectName("pbGeri")
        self.pbParaCek = QtWidgets.QPushButton(paraCekme)
        self.pbParaCek.setGeometry(QtCore.QRect(160, 400, 100, 32))
        self.pbParaCek.setObjectName("pbParaCek")

        self.retranslateUi(paraCekme)
        self.cmParaTuru.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(paraCekme)

    def retranslateUi(self, paraCekme):
        _translate = QtCore.QCoreApplication.translate
        paraCekme.setWindowTitle(_translate("paraCekme", "Form"))
        self.label_2.setText(_translate("paraCekme", "<html><head/><body><p align=\"center\">Para Türü</p></body></html>"))
        self.label_3.setText(_translate("paraCekme", "<html><head/><body><p align=\"center\">Para Tutarı</p></body></html>"))
        self.cmParaTuru.setItemText(0, _translate("paraCekme", "Dolar"))
        self.cmParaTuru.setItemText(1, _translate("paraCekme", "Tl"))
        self.label_4.setText(_translate("paraCekme", "TC Numarası"))
        self.label.setText(_translate("paraCekme", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; color:#0433ff;\">Para Çekme İşlemi</span></p></body></html>"))
        self.pbGeri.setText(_translate("paraCekme", "Geri"))
        self.pbParaCek.setText(_translate("paraCekme", "Para Çekme"))
