# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paraGonder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_paraGonder(object):
    def setupUi(self, paraGonder):
        paraGonder.setObjectName("paraGonder")
        paraGonder.resize(424, 550)
        self.lnTC = QtWidgets.QLineEdit(paraGonder)
        self.lnTC.setGeometry(QtCore.QRect(210, 110, 113, 21))
        self.lnTC.setObjectName("lnTC")
        self.label_2 = QtWidgets.QLabel(paraGonder)
        self.label_2.setGeometry(QtCore.QRect(110, 175, 71, 20))
        self.label_2.setObjectName("label_2")
        self.cmParaTuru = QtWidgets.QComboBox(paraGonder)
        self.cmParaTuru.setGeometry(QtCore.QRect(100, 230, 103, 41))
        self.cmParaTuru.setObjectName("cmParaTuru")
        self.cmParaTuru.addItem("")
        self.cmParaTuru.addItem("")
        self.pbParaGonder = QtWidgets.QPushButton(paraGonder)
        self.pbParaGonder.setGeometry(QtCore.QRect(160, 400, 100, 32))
        self.pbParaGonder.setObjectName("pbParaGonder")
        self.label_3 = QtWidgets.QLabel(paraGonder)
        self.label_3.setGeometry(QtCore.QRect(230, 175, 101, 16))
        self.label_3.setObjectName("label_3")
        self.pbGeri = QtWidgets.QPushButton(paraGonder)
        self.pbGeri.setGeometry(QtCore.QRect(160, 510, 100, 32))
        self.pbGeri.setObjectName("pbGeri")
        self.label = QtWidgets.QLabel(paraGonder)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 61))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(paraGonder)
        self.label_4.setGeometry(QtCore.QRect(100, 110, 91, 21))
        self.label_4.setObjectName("label_4")
        self.labelDurum = QtWidgets.QLabel(paraGonder)
        self.labelDurum.setGeometry(QtCore.QRect(160, 380, 101, 20))
        self.labelDurum.setText("")
        self.labelDurum.setObjectName("labelDurum")
        self.lnParaMiktari = QtWidgets.QLineEdit(paraGonder)
        self.lnParaMiktari.setGeometry(QtCore.QRect(220, 240, 113, 21))
        self.lnParaMiktari.setObjectName("lnParaMiktari")
        self.label_5 = QtWidgets.QLabel(paraGonder)
        self.label_5.setGeometry(QtCore.QRect(110, 300, 201, 21))
        self.label_5.setObjectName("label_5")
        self.lnGIBAN = QtWidgets.QLineEdit(paraGonder)
        self.lnGIBAN.setGeometry(QtCore.QRect(140, 350, 151, 21))
        self.lnGIBAN.setObjectName("lnGIBAN")

        self.retranslateUi(paraGonder)
        self.cmParaTuru.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(paraGonder)

    def retranslateUi(self, paraGonder):
        _translate = QtCore.QCoreApplication.translate
        paraGonder.setWindowTitle(_translate("paraGonder", "Form"))
        self.label_2.setText(_translate("paraGonder", "<html><head/><body><p align=\"center\">Para Türü</p></body></html>"))
        self.cmParaTuru.setItemText(0, _translate("paraGonder", "Dolar"))
        self.cmParaTuru.setItemText(1, _translate("paraGonder", "Tl"))
        self.pbParaGonder.setText(_translate("paraGonder", "Para Gönder"))
        self.label_3.setText(_translate("paraGonder", "<html><head/><body><p align=\"center\">Para Tutarı</p></body></html>"))
        self.pbGeri.setText(_translate("paraGonder", "Geri"))
        self.label.setText(_translate("paraGonder", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; color:#0433ff;\">Para Gönderme İşlemi</span></p></body></html>"))
        self.label_4.setText(_translate("paraGonder", "TC Numarası"))
        self.label_5.setText(_translate("paraGonder", "Para Gönderilecek IBAN Numarsı"))
