# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paraYatir.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_paraYatir(object):
    def setupUi(self, paraYatir):
        paraYatir.setObjectName("paraYatir")
        paraYatir.resize(424, 550)
        self.cmParaTuru = QtWidgets.QComboBox(paraYatir)
        self.cmParaTuru.setGeometry(QtCore.QRect(80, 250, 103, 41))
        self.cmParaTuru.setObjectName("cmParaTuru")
        self.cmParaTuru.addItem("")
        self.cmParaTuru.addItem("")
        self.lnParaMiktari = QtWidgets.QLineEdit(paraYatir)
        self.lnParaMiktari.setGeometry(QtCore.QRect(190, 260, 113, 21))
        self.lnParaMiktari.setObjectName("lnParaMiktari")
        self.label = QtWidgets.QLabel(paraYatir)
        self.label.setGeometry(QtCore.QRect(30, 20, 201, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(paraYatir)
        self.label_2.setGeometry(QtCore.QRect(90, 190, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(paraYatir)
        self.label_3.setGeometry(QtCore.QRect(190, 190, 101, 16))
        self.label_3.setObjectName("label_3")
        self.pbParaYatir = QtWidgets.QPushButton(paraYatir)
        self.pbParaYatir.setGeometry(QtCore.QRect(160, 400, 100, 32))
        self.pbParaYatir.setObjectName("pbParaYatir")
        self.pbGeri = QtWidgets.QPushButton(paraYatir)
        self.pbGeri.setGeometry(QtCore.QRect(160, 510, 100, 32))
        self.pbGeri.setObjectName("pbGeri")
        self.lnTC = QtWidgets.QLineEdit(paraYatir)
        self.lnTC.setGeometry(QtCore.QRect(190, 135, 113, 21))
        self.lnTC.setObjectName("lnTC")
        self.label_4 = QtWidgets.QLabel(paraYatir)
        self.label_4.setGeometry(QtCore.QRect(90, 135, 91, 21))
        self.label_4.setObjectName("label_4")
        self.labelDurum = QtWidgets.QLabel(paraYatir)
        self.labelDurum.setGeometry(QtCore.QRect(180, 300, 101, 20))
        self.labelDurum.setText("")
        self.labelDurum.setObjectName("labelDurum")

        self.retranslateUi(paraYatir)
        self.cmParaTuru.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(paraYatir)

    def retranslateUi(self, paraYatir):
        _translate = QtCore.QCoreApplication.translate
        paraYatir.setWindowTitle(_translate("paraYatir", "Form"))
        self.cmParaTuru.setItemText(0, _translate("paraYatir", "Dolar"))
        self.cmParaTuru.setItemText(1, _translate("paraYatir", "Tl"))
        self.label.setText(_translate("paraYatir", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; color:#0433ff;\">Para Yatirma İşlemi</span></p></body></html>"))
        self.label_2.setText(_translate("paraYatir", "<html><head/><body><p align=\"center\">Para Türü</p></body></html>"))
        self.label_3.setText(_translate("paraYatir", "<html><head/><body><p align=\"center\">Para Tutarı</p></body></html>"))
        self.pbParaYatir.setText(_translate("paraYatir", "Para Yatir"))
        self.pbGeri.setText(_translate("paraYatir", "Geri"))
        self.label_4.setText(_translate("paraYatir", "TC Numarası"))
