# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KayitEkrani(object):
    def setupUi(self, KayitEkrani):
        KayitEkrani.setObjectName("KayitEkrani")
        KayitEkrani.resize(424, 550)
        self.pbKayit = QtWidgets.QPushButton(KayitEkrani)
        self.pbKayit.setGeometry(QtCore.QRect(140, 290, 131, 31))
        self.pbKayit.setObjectName("pbKayit")
        self.pbGeri = QtWidgets.QPushButton(KayitEkrani)
        self.pbGeri.setGeometry(QtCore.QRect(170, 370, 71, 32))
        self.pbGeri.setObjectName("pbGeri")
        self.labelDurum = QtWidgets.QLabel(KayitEkrani)
        self.labelDurum.setGeometry(QtCore.QRect(170, 330, 131, 21))
        self.labelDurum.setText("")
        self.labelDurum.setObjectName("labelDurum")
        self.layoutWidget = QtWidgets.QWidget(KayitEkrani)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 90, 191, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lneYKadi = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneYKadi.setObjectName("lneYKadi")
        self.verticalLayout.addWidget(self.lneYKadi)
        self.lneYKsoyadi = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneYKsoyadi.setObjectName("lneYKsoyadi")
        self.verticalLayout.addWidget(self.lneYKsoyadi)
        self.lneYKsifre = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneYKsifre.setObjectName("lneYKsifre")
        self.verticalLayout.addWidget(self.lneYKsifre)
        self.lneYKtc = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneYKtc.setObjectName("lneYKtc")
        self.verticalLayout.addWidget(self.lneYKtc)
        self.lneYKtlbakiye = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneYKtlbakiye.setObjectName("lneYKtlbakiye")
        self.verticalLayout.addWidget(self.lneYKtlbakiye)
        self.lneYKdovizbakiye = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneYKdovizbakiye.setObjectName("lneYKdovizbakiye")
        self.verticalLayout.addWidget(self.lneYKdovizbakiye)
        self.layoutWidget1 = QtWidgets.QWidget(KayitEkrani)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 90, 131, 181))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label1 = QtWidgets.QLabel(self.layoutWidget1)
        self.label1.setObjectName("label1")
        self.verticalLayout_2.addWidget(self.label1)
        self.label1_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label1_2.setObjectName("label1_2")
        self.verticalLayout_2.addWidget(self.label1_2)
        self.label3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label3.setObjectName("label3")
        self.verticalLayout_2.addWidget(self.label3)
        self.label4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label4.setObjectName("label4")
        self.verticalLayout_2.addWidget(self.label4)
        self.label2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label2.setObjectName("label2")
        self.verticalLayout_2.addWidget(self.label2)
        self.label2_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label2_2.setObjectName("label2_2")
        self.verticalLayout_2.addWidget(self.label2_2)

        self.retranslateUi(KayitEkrani)
        QtCore.QMetaObject.connectSlotsByName(KayitEkrani)

    def retranslateUi(self, KayitEkrani):
        _translate = QtCore.QCoreApplication.translate
        KayitEkrani.setWindowTitle(_translate("KayitEkrani", "Form"))
        self.pbKayit.setText(_translate("KayitEkrani", "Kayıt"))
        self.pbGeri.setText(_translate("KayitEkrani", "Geri"))
        self.label1.setText(_translate("KayitEkrani", "Kullanici Adı"))
        self.label1_2.setText(_translate("KayitEkrani", "Kullanici Soy Adı"))
        self.label3.setText(_translate("KayitEkrani", "Kullanici Şifre"))
        self.label4.setText(_translate("KayitEkrani", "Kullanici TC"))
        self.label2.setText(_translate("KayitEkrani", "Kullanici TL Bakiye"))
        self.label2_2.setText(_translate("KayitEkrani", "kullanici Dollar Bakiye"))
